@Library('shared') _
pipeline{
    agent {label "demo"}
    stages{
        stage('clone'){
            steps{
                script{
                    clone("https://github.com/hitanshuyadav/node-todo-cicd.git","master")
                }
            }
        }
        stage('build'){
            steps{
                script{
                    build("new-todo-app","testing")
                }
            }
        }
        stage('push'){
            steps{
                script{
                    push("jenkinsCred","testing","new-todo-app")
                }
            }
        }
         stage('deploy'){
            steps{
                script{
                    deploy("new-todo-app","testing","80","8000")
                }
            }
        }
    }
}
